export { default as Slanted } from './Slanted.svelte';
export { default as LogoType } from './LogoType.svelte';
export { default as LogoTagline } from './LogoTagline.svelte';
export { default as ColorSpan } from './ColorSpan.svelte';
export { default as Heading } from './Heading.svelte';
export { default as SubHeading } from './SubHeading.svelte';
export { default as Notice } from './Notice.svelte';
export { default as Prose } from './Prose.svelte';
export { default as Text } from './Text.svelte';
